CREATE TABLE sports (
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	sport_key VARCHAR(255) NOT NULL,
	name VARCHAR(255) NULL
) ENGINE = INNODB;

CREATE TABLE leagues (
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	league_key VARCHAR(255) NOT NULL,
	sport_id INTEGER NOT NULL,
	name VARCHAR(255) NULL,
	nickname VARCHAR(255) NULL
) ENGINE = INNODB;

ALTER TABLE seasons 
	CHANGE season_key season_key VARCHAR(255)
	ADD name VARCHAR(255) AFTER season_key 
;

CREATE TABLE conferences (
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	conference_key VARCHAR(255) NOT NULL,
	league_id INTEGER NOT NULL,
	name VARCHAR(255) NULL,
	shortname VARCHAR(255) NULL
) ENGINE = INNODB;

CREATE TABLE divisions (
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	division_key VARCHAR(255) NOT NULL,
	conference_id INTEGER NOT NULL,
	name VARCHAR(255) NULL,
	active TINYINT(1) NULL
) ENGINE = INNODB;
